# Generated by Django 5.2.8 on 2025-11-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_cosecha', models.DateField()),
                ('cantidad', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cosechas.cultivo')),
            ],
        ),
    ]
