# Generated by Django 5.2.8 on 2025-12-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosechas', '0001_initial'),
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosecha',
            name='cultivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo'),
        ),
        migrations.DeleteModel(
            name='Cultivo',
        ),
    ]
